# Generated by Django 5.1.2 on 2024-10-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                (
                    "local_government",
                    models.CharField(
                        choices=[
                            ("Ifako-Ijaiye", "Ifako-Ijaiye"),
                            ("Koshofe", "Koshofe"),
                            ("Agege", "Agege"),
                        ],
                        default="Agege",
                        max_length=50,
                        verbose_name="Local Government you reside",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Adamawa", "Adamawa"),
                            ("Akwa Ibom", "Akwa Ibom"),
                            ("Anambra", "Anambra"),
                            ("Bauchi", "Bauchi"),
                            ("Bayelsa", "Bayelsa"),
                            ("Benue", "Benue"),
                            ("Borno", "Borno"),
                            ("Calabar", "Calabar"),
                            ("Delta", "Delta"),
                            ("Ebonyi", "Ebonyi"),
                            ("Edo", "Edo"),
                            ("Lagos", "Lagos"),
                            ("Ogun", "Ogun"),
                            ("Rivers", "Rivers"),
                            ("Abuja", "Abuja"),
                        ],
                        default="Ogun",
                        max_length=50,
                        verbose_name="State you reside?",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=6,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, verbose_name="Write a few things about yourself"
                    ),
                ),
                (
                    "phone",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Phone Number"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
