# Generated by Django 5.1.2 on 2024-10-25 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("workers", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(verbose_name="Your Budget in Naira"),
                ),
                ("active", models.BooleanField(default=False)),
                ("state", models.CharField(max_length=50)),
                ("local_government", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workers.job",
                        verbose_name="Select a service",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seeks",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
    ]
