# Generated by Django 4.1.2 on 2023-03-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seek', '0003_alter_seek_budget_alter_seek_job_alter_seek_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seek',
            options={'ordering': ['-start_time']},
        ),
    ]
